export const GET_ALL_LOCATIONS_PENDING = 'GET_ALL_LOCATIONS_PENDING'
export const GET_ALL_LOCATIONS_FAILED = 'GET_ALL_LOCATIONS_FAILED'
export const GET_ALL_LOCATIONS_SUCCESS = 'GET_ALL_LOCATIONS_SUCCESS'