export const GET_ALL_CARS_PENDING = 'GET_ALL_CARS_PENDING'
export const GET_ALL_CARS_FAILED = 'GET_ALL_CARS_FAILED'
export const GET_ALL_CARS_SUCCESS = 'GET_ALL_CARS_SUCCESS'

export const GET_ONE_CAR_PENDING = 'GET_ONE_CAR_PENDING'
export const GET_ONE_CAR_SUCCESS = 'GET_ONE_CAR_SUCCESS'
export const GET_ONE_CAR_FAILED = 'GET_ONE_CAR_FAILED'

export const ADD_NEW_CAR_PENDING = 'ADD_NEW_CAR_PENDING'
export const ADD_NEW_CAR_SUCCESS = 'ADD_NEW_CAR_SUCCESS'
export const ADD_NEW_CAR_FAILED = 'ADD_NEW_CAR_FAILED'

export const DELETE_CAR_PENDING = 'DELETE_CAR_PENDING'
export const DELETE_CAR_SUCCESS = 'DELETE_CAR_SUCCESS'
export const DELETE_CAR_FAILED = 'DELETE_CAR_FAILED'

export const EDIT_ONE_CAR_PENDING = 'EDIT_ONE_CAR_PENDING'
export const EDIT_ONE_CAR_SUCCESS = 'EDIT_ONE_CAR_SUCCESS'
export const EDIT_ONE_CAR_FAILED = 'EDIT_ONE_CAR_FAILED'

export const CLEAR_ONECAR_STATE_PENDING = 'CLEAR_ONECAR_STATE_PENDING'
export const CLEAR_ONECAR_STATE_SUCCESS = 'CLEAR_ONECAR_STATE_SUCCESS'
export const CLEAR_ONECAR_STATE_FAILED = 'CLEAR_ONECAR_STATE_FAILED'